package com.mars.web.gov.search.inter;

/**
 * Adapter for data mapping, converting inner data to data readable.
 * @author  tiger Liu
 * @version Demo
 * @date    Jun 26, 2015
 */
public interface DataDealAdapterInterface {
	/**
	 * 
	 * For each data field generated by FDA using inner value, for example, sexid could be 0, meaning male. 
	 * Therefore, a mapping adapter is using to change those value to readable value.
	 * 
	 * @param strValue inner value from FDA searching APIs.
	 * @return caption of the field. Once no such data returning, return the parameter passed
	 */
	String GetDisplayCaptionByValue(String strValue) ;
	
	/**
	 * For displaying data as a grid, column name and title is required for JSON. 
	 * Each class is used for one field adapter.
	 * 
	 * For cases, columnName is required
	 * 
	 * @author tiger Liu	 *  
	 * @param  strColumnNameInner Inner name from FDA searching result
	 * @return Defined Column Title info.
	 */
	String GetTitleForColumn(String strColumnNameInner) ;  
	 
	/**
	 * Set a width value to the Column.
	 * 
	 * Configuration can be configurated by Enum or properties files. To get value from ENUM or other 
	 * container, a inner name is required. 
	 * 
	 * @param strColumnNameInner Column inner name, could be like json.result.patient.ageset
	 * @return
	 */
	String GetWidthForColumn(String strColumnNameInner) ;
}
